##  Multiple Linear Regression 

In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

import statsmodels.api as sm
from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression

In [84]:
data = pd.read_csv("1.02.+Multiple+linear+regression.csv")

In [85]:
data

SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [86]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [87]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [88]:
# Declare the Dependent and Independent Variable #
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [89]:
reg = LinearRegression()

In [90]:
reg.fit(x,y)

LinearRegression()

In [91]:
x.shape

(84, 2)

In [92]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [93]:
reg.intercept_

0.29603261264909486

In [94]:
# x = sm.add_constant(x)
# results = sm.OLS(y,x).fit()
# results.summary()


## Calculating the R-Squared #
## This function calculates the R-Squared of a Linear Regression #


In [95]:
reg.score(x,y)

0.40668119528142843

## Formula for Adjusted R^2
$R^2_(adj.) = 1 - (1-R^2)*\frac(n-1)(n-p-1)$

In [96]:
reg.score(x,y)

0.40668119528142843

In [97]:
x.shape

(84, 2)

In [98]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjuster_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjuster_r2

0.39203134825134023

## How to detect the variable which are unneded in the models?
## Feature Selection(F-regression)
## Feature selection simplifies the models, improve speeds and prevents a series of unwanted issues arising from having too many features. 
## If a variable has a P- value > 0.05,we can disregard it.

In [99]:
from sklearn.feature_selection import f_regression

## In Output first one contain f-statistics for each of the regression, second one contain the corresponding p-values#

In [100]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

## Here extracting only p-values#

In [101]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

## These are the univariant p-values reached from the simple linear models,They do not reflect the interconnection of the features in our multiple linear regression.

## In output first one refers to the 'SAT' and second one refers to the 'Rand 1,2,3'

In [102]:
p_values.round(3)
#In output forst one refers to the 'SAT' and second one refers to the 'Rand 1,2,3'

array([0.   , 0.676])

## Creating a Summary table

In [103]:
#reg_summary = pd.DataFrame(data=['SAT','Rand 1,2,3'],columns=['Features'])#Both
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])#are same.
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [104]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['P-Values'] = p_values.round(3)

In [105]:
reg_summary
#p-values are one of the best ways to determine if a variable is redundant#

Features  Coefficients  P-Values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

## The common problem when working with numerical data is  Difference in Magnitudes.

## An easy fix for this issue is standardization, also known as feature scaling or normalization.

## Standardization is the process of transforming the data we are working with into a standard scale.

## STANDARDIZATION

In [108]:
from sklearn.preprocessing import StandardScaler

In [109]:
scaler = StandardScaler()
# Here we have created the empty StandardScaler object

In [110]:
#This line will calculate the mean and standard deviation of each feature.
scaler.fit(x,y)

StandardScaler()

In [111]:
#Transform the unskilled inputs using the information contained in scalar in simple words, we subtract the mean and divide by the standard deviation for each feature.
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

## Regression with Scaled Features

In [112]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [113]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [114]:
reg.intercept_

3.330238095238095

## Creating a Summary Table

In [115]:
reg.summary = pd.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']],columns=['Features'])
reg.summary['weights']= reg.intercept_,reg.coef_[0],reg.coef_[1]
reg.summary

Features   weights
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

## Making predictions with the standardized coefficients(weight)

In [116]:
new_data = pd.DataFrame(data= [[1700,2],[1000,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1000           1

In [117]:
reg.predict(new_data.values)

array([295.39979563, 175.13710077])

In [118]:
new_data_scaled = scaler.transform(new_data)

In [119]:
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-8.13493924, -1.24637147]])

In [120]:
reg.predict(new_data_scaled)

array([3.09051403, 1.94130459])

## What if we remove the 'Rand 1,2,3' variable?

In [121]:
reg_simple =LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [82]:
reg_simple.predict((new_data_scaled[:,0]).reshape(-1,1))

array([3.08970998, 1.93072835])